### ISSUE TITLE
Ideias

### ISSUE THREAD

**Issue by michelmelo** [gravataLonga/pitly#1]
Estatisticas:

- por horas
- por dias
- por mes

**Comment by gravataLonga** [comment]
@michelmelo sim, por acaso estava a pensar nisso na altura que estive a fazer. Está a pensar fazer algo do genero:  

`{"count":2,"data":{"09":0,"10":1,"11":2,"12":0,"13":5}}`

**Comment by michelmelo** [comment]
@gravataLonga sim. seria fixe.

**Comment by Fatih90** [comment]
italiano sigareto

**Comment by gravataLonga** [comment]
@Fatih90 Sorry can't understand italiano, but i think you said something like "Follow me" ? Any way, i have doing a lot of refactoring, you can see here:  

[Reafactoring API RESPONSE](https://github.com/gravataLonga/pitly/blob/master/app/Http/Controllers/ShorterController.php#L13-L16)   

Tell me what you thing @Fatih90.
